# Generated by Django 4.2.8 on 2023-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('age', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('d', models.IntegerField()),
                ('e', models.IntegerField()),
                ('f', models.IntegerField()),
            ],
        ),
    ]
