# Generated by Django 4.2.8 on 2023-12-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='day',
            new_name='date',
        ),
    ]
