# Generated by Django 4.2.8 on 2023-12-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_rename_day_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
