# Generated by Django 4.2.8 on 2023-12-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_alter_data_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='d',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='date',
            new_name='Day',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='e',
            new_name='E',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='f',
            new_name='F',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='gender',
            new_name='Gender',
        ),
    ]
