# Generated by Django 4.2.8 on 2023-12-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_rename_a_data_a_rename_age_data_age_rename_b_data_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Day',
            field=models.DateField(),
        ),
    ]
